name: manzac_app
description: "Logistica Manzac"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  material_color_gen: ^2.0.0
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.12
  image: ^4.5.3
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_spinkit: ^5.2.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
#  change_app_package_name: ^1.4.0
#  dart run change_app_package_name:main com.mtgdevs.manzaclogistic

flutter:
  uses-material-design: true

  assets:
    - assets/logo-manzac.png