// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:manzac_app/app/data/models/local_storage/local_storage.dart';
import 'package:manzac_app/app/data/models/reportes/reporte_alta_local.dart';
import 'package:manzac_app/app/data/models/reportes/reporte_danio.dart';
import 'package:manzac_app/app/data/models/reportes/reporte_entrada.dart';
import 'package:manzac_app/app/data/models/reportes/reporte_imagenes.dart';
import 'package:manzac_app/app/data/models/reportes/reporte_salida.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocalStorageAdapter());
    registerAdapter(ReporteAltaLocalAdapter());
    registerAdapter(ReporteDanioAdapter());
    registerAdapter(ReporteEntradaAdapter());
    registerAdapter(ReporteImagenesAdapter());
    registerAdapter(ReporteSalidaAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LocalStorageAdapter());
    registerAdapter(ReporteAltaLocalAdapter());
    registerAdapter(ReporteDanioAdapter());
    registerAdapter(ReporteEntradaAdapter());
    registerAdapter(ReporteImagenesAdapter());
    registerAdapter(ReporteSalidaAdapter());
  }
}
